#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

GPIO_PIN=138
DELAY_LOW=3

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/gpio138-ctl start
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    /usr/bin/gpio138-ctl stop
}

reload_service() {
    /usr/bin/gpio138-ctl restart
}
