name: ImageBuilder Build

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Extra packages'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        run: echo "Inputs test - packages: ${{ github.event.inputs.packages }}"