name: ImageBuilder Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Create test file
        run: |
          mkdir -p output
          echo "test" > output/test.txt
          ls -lh output/

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: output/
          retention-days: 30
